### ISSUE TITLE
Must not change document outside command or undo-transparent action. ...

### ISSUE THREAD

**Issue by happylynx** [ArcBees/gwtp-idea-plugin#48]
Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor

Idea error dialog popped up after confirmation of dialog to create new GWTP presenter. Neither of presenter radio button triple was selected, 'Add onReset()' was checked, Name was entered, no other changes to dialog default. The action was invoked on standard gwtp demo project from following archetype:

```
mvn archetype:generate -DarchetypeGroupId=com.arcbees.archetypes -DarchetypeRepository=https://oss.sonatype.org/content/repositories/snapshots/ -DarchetypeArtifactId=gwtp-basic-archetype -DarchetypeVersion=1.0-SNAPSHOT
```

The bug appears repeatedly.

Plugin version: 1.1.0
Idea version: 13.1.5

Content of _Details_ tab of Idea error dialog:

```
Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:519)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:292)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:236)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:195)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:695)
    at com.intellij.psi.formatter.FormatterUtil.replaceWhiteSpace(FormatterUtil.java:332)
    at com.intellij.psi.impl.source.codeStyle.PsiBasedFormatterModelWithShiftIndentInside.replaceWithPsiInLeaf(PsiBasedFormatterModelWithShiftIndentInside.java:115)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.a(PsiBasedFormattingModel.java:101)
    at com.intellij.psi.formatter.PsiBasedFormattingModel.replaceWhiteSpace(PsiBasedFormattingModel.java:64)
    at com.intellij.formatting.FormatProcessor.a(FormatProcessor.java:389)
    at com.intellij.formatting.FormatProcessor.access$2400(FormatProcessor.java:37)
    at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1420)
    at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1246)
    at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:244)
    at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:835)
    at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:240)
    at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:194)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
    at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:104)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:91)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$12$1.run(CreatePresenterAction.java:508)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$12.run(CreatePresenterAction.java:503)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:596)
    at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:551)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:298)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:236)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:195)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:695)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:205)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:540)
    at com.intellij.psi.impl.source.tree.java.JavaFileElement.replaceChildInternal(JavaFileElement.java:97)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:196)
    at com.intellij.psi.impl.source.JavaStubPsiElement.replace(JavaStubPsiElement.java:150)
    at com.intellij.psi.impl.source.codeStyle.JavaCodeStyleManagerImpl.optimizeImports(JavaCodeStyleManagerImpl.java:117)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$13$1.run(CreatePresenterAction.java:520)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$13.run(CreatePresenterAction.java:517)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:596)
    at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:551)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:298)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:236)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:195)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:695)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:205)
    at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:540)
    at com.intellij.psi.impl.source.tree.java.JavaFileElement.replaceChildInternal(JavaFileElement.java:97)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:196)
    at com.intellij.psi.impl.source.JavaStubPsiElement.replace(JavaStubPsiElement.java:150)
    at com.intellij.psi.impl.source.codeStyle.JavaCodeStyleManagerImpl.optimizeImports(JavaCodeStyleManagerImpl.java:117)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$13$1.run(CreatePresenterAction.java:520)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$13.run(CreatePresenterAction.java:517)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



com.intellij.util.IncorrectOperationException: Must not change document outside command or undo-transparent action. See com.intellij.openapi.command.WriteCommandAction or com.intellij.openapi.command.CommandProcessor
    at com.intellij.openapi.editor.impl.DocumentImpl.e(DocumentImpl.java:758)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
    at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:709)
    at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:494)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:295)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.access$100(PsiToDocumentSynchronizer.java:37)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$6.syncDocument(PsiToDocumentSynchronizer.java:264)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer$1.run(PsiToDocumentSynchronizer.java:104)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:128)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.a(PsiToDocumentSynchronizer.java:101)
    at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:261)
    at com.intellij.pom.core.impl.PomModelImpl.a(PomModelImpl.java:236)
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:195)
    at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:169)
    at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:646)
    at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:753)
    at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:82)
    at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:532)
    at com.intellij.psi.impl.source.tree.java.ImportListElement.addInternal(ImportListElement.java:45)
    at com.intellij.psi.impl.source.JavaStubPsiElement.addAfter(JavaStubPsiElement.java:97)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$4$1.run(CreatePresenterAction.java:293)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.arcbees.plugin.idea.wizards.createpresenter.CreatePresenterAction$4.run(CreatePresenterAction.java:288)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:165)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by branflake2267** [comment]
Probably needs to be wrapped in an async call, hm

**Comment by olafleur** [comment]
Closing, as this issue is more than a year old. Feel free to reopen if you still have the issue with the current version.
