### ISSUE TITLE
New Project -> Second "Archetype" list stays empty, IllegalStateException at fetchArchetypes about unsupported Content-Type

### ISSUE THREAD

**Issue by Niko-O** [ArcBees/gwtp-idea-plugin#83]
Plugin version: 1.2.1
IDE version: IntelliJ IDEA 2021.1.2 (Community Edition) Build #IC-221.7442.40

Steps to reproduce:
* File ->New -> Project...
* Select GWTP
* Select Project SDK (In my case, I use AdoptOpenJDK 16.0.1)
* Uncheck "Create from archetype" OR check it and select a random entry
* Click "Next"

The "Select Archetype" list is never populated. The following Exception is logged to idea.log:

        2021-06-11 07:13:43,058 [ 712823]  ERROR - plication.impl.ApplicationImpl - Cannot parse object because no supported Content-Type was not specified in response. Content-Type was 'text/html; charset=UTF-8'. 
        java.lang.IllegalStateException: Cannot parse object because no supported Content-Type was not specified in response. Content-Type was 'text/html; charset=UTF-8'.
	        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:244)
	        at com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:78)
	        at com.jayway.restassured.internal.mapping.ObjectMapping$deserialize.call(Unknown Source)
	        at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:206)
	        at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:153)
	        at com.arcbees.plugin.idea.wizards.createproject.FetchArchetypes.fetchArchetypes(FetchArchetypes.java:51)
	        at com.arcbees.plugin.idea.wizards.createproject.CreateProjectWizard$1.run(CreateProjectWizard.java:113)
	        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	        at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	        at java.base/java.security.AccessController.doPrivileged(Native Method)
	        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	        at java.base/java.lang.Thread.run(Thread.java:829)
        2021-06-11 07:13:43,059 [ 712824]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2021.1.2  Build #IC-211.7442.40 
        2021-06-11 07:13:43,059 [ 712824]  ERROR - plication.impl.ApplicationImpl - JDK: 11.0.11; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o. 
        2021-06-11 07:13:43,059 [ 712824]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
        2021-06-11 07:13:43,059 [ 712824]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: GWT-Platform (GWTP) IntelliJ IDEA Plugin version: 1.2.1 
        2021-06-11 07:13:43,059 [ 712824]  ERROR - plication.impl.ApplicationImpl - Last Action: NewProject 

This has happened before in issue #61

**Comment by christiangoudreau** [comment]
Help is welcome since it's not being actively developed anymore
